package com.lazada.model.product;

public class FinalInfo extends BaseInfo{

	public void backToInit() {
		
		this.oneItemStart = false;
		this.getName = false;
		this.getDescription = false;
		this.getDescriptionCode=false;
		this.getShort_description= false;
		this.getShort_descriptioncode= false;
		this.getPrice = false;
		this.getSpecial_price = false;
		this.getSellerSku = false;
		this.getPackage_content = false;
		this.getMainImage = false;
		this.getImage2 = false;
		this.getImage3 = false;
		this.getImage4= false;
		this.getImage5 = false;
		this.getImage6 = false;
		this.getImage7 = false;
		this.getImage8 = false;
		this.getLink = false;
		this.getComment = false;
		this.getSize = false;
		this.getcategory = false;
		this.getBrand = false;
		this.getStore = false;
		this.getLocation = false;
		this.getCompatibility=false;
		this.getDiscuss=false;
		this.getSalenum=false;
		this.getsmallimage1=false;
		this.getsmallimage2=false;
		this.getsmallimage3=false;
		this.getsmallimage4=false;
		this.getsmallimage5=false;
		this.getsmallimage6=false;
		this.getsmallimage7=false;
		this.getsmallimage8=false;
		this.getsmallimage9=false;
		this.getsmallimage10=false;
		this.getsmallimage11=false;
		this.getsmallimage12=false;
		this.getsmallimage14=false;
		this.getsmallimage15=false;
		this.getVideoLink=false;
		
		this.name = "";
		this.description= "";
		this.descriptioncode="";
		this.short_description = "";
		this.short_descriptioncode="";
		this.price = "";
		this.special_price = "";
		this.sellersku = "";
		this.package_content = "";
		this.mainimage = "";
		this.image2 = "";
		this.image3 = "";
		this.image4 = "";
		this.image5 = "";
		this.image6 = "";
		this.image7 = "";
		this.image8 = "";
		this.link = "";
		this.comment = "";
		this.discuss="";
		this.salenum="";
		this.size="";
		this.category="";
		this. brand="";
		this.store="";
		this.location="";
		this.compatibility="";
		this.smallimage1="";
		this.smallimage2="";
		this.smallimage3="";
		this.smallimage4="";
		this.smallimage5="";
		this.smallimage6="";
		this.smallimage7="";
		this.smallimage8="";
		this.smallimage9="";
		this.smallimage10="";
		this.smallimage11="";
		this.smallimage12="";
		this.smallimage13="";
		this.smallimage14="";
		this.smallimage15="";
		this.videoLink="";
	}
}
